config/routes.rb
Artflow::Application.routes.draw do

  devise_for :clients
  devise_for :designers
  devise_for :users

  resources :campaigns
  resources :clients
  resources :comments
  resources :creations do
    member do
      get 'permissions'
    end
  end
  resources :designers
  resources :plans
  resources :projects
  resources :project_assignments
  resources :subscriptions
  

  root :to => 'pages#home'

end

app/models/creation.rb
#---
# Excerpted from "The Rails View",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/warv for more book information.
#---
class Creation < ActiveRecord::Base
  has_attached_file :file, styles: {
    thumbnail:  "100x100#",
    small:      "150x150>",
    medium:     "200x200"
  }
  belongs_to :estimate
  belongs_to :client
  belongs_to :project
  belongs_to :designer
  has_many :comments

  validates :name, :description,
            :project_id, presence: true

  validates :name, :description, :project_id, presence: true
  
  before_validation :copy_client_id, on: :create

  def title
    name
  end
  
  def default_image?
    file.exists?
  end

  def default_image
    file.url(:thumbnail)
  end

  def thumbnail?
    file.exists?
  end
  
  def approvable?
    status == 'awaiting_approval'
  end

  def file_type
    file.content_type
  end

  private

  def copy_client_id
    write_attribute(:client_id, project.client_id)
  end

end

app/controllers/creations_controller.rb
#---
# Excerpted from "The Rails View",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/warv for more book information.
#---
class CreationsController < ApplicationController
  def index
    @creations = Creation.all
  end

  def show
    @creation = Creation.find(params[:id])
  end

  def create
    @creation = Creation.new(params[:creation])
    if @creation.save
      flash[:notice] = "Creation added!"
      redirect_to @creation
    else
      flash.now[:alert] = "Could not save creation!"
      render action: 'new'
    end
  end

  def permissions
    @creation = Creation.find(params[:id])
  end

end

app/helpers/creations_helper.rb
#---
# Excerpted from "The Rails View",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/warv for more book information.
#---
module CreationsHelper
end

app/views/creations/index.html.erb
<h2>Creations</h2>

<%# START_HIGHLIGHT %>
<%= currently_at 'Creations' %>
<%# END_HIGHLIGHT %>

app/views/creations/new.html.erb
<h1>Add Creation</h1>

<% currently_at 'Creations' %>

<%# STUB: This page isn't covered in the book. %>

app/views/creations/permissions.html.erb
<nav id="breadcrumbs" itemtype="http://schema.org/WebPage"
                      itemprop="breadcrumb"><ul>
  <li><%= link_to 'Creations', creations_path %></li>
  <li><%= link_to truncate(@creation.name), @creation %></li>
  <li><%= link_to 'Edit', edit_creations_path(@creation) %></li>
  <li>Permissions</li>
</ul></nav>

app/views/creations/show.html.erb
<% content_for :functional_nav do %>
  <li><%= link_to 'Edit this creation', @creation %></li>
<% end %>