config/routes.rb
Artflow::Application.routes.draw do

  devise_for :clients
  devise_for :designers
  devise_for :users

  resources :campaigns
  resources :clients
  resources :comments
  resources :creations do
    member do
      get 'permissions'
    end
  end
  resources :designers
  resources :plans
  resources :projects
  resources :project_assignments
  resources :subscriptions
  

  root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
  <footer id="page_footer">
    <ul>
      <li><%= link_to "Contact", "" %></li>
      <li><%= link_to "Help", "" %></li>
      <li><%= link_to "File a Bug", "" %></li>
    </ul>
    <p>&copy; 2011 AwesomeCo. All Rights Reserved. All Wrongs Reversed.</p>
  </footer>

app/views/layouts/_header.html.erb
  <header id="page_header" role="banner">
    <nav id="utility">
      <p>
        You are logged in as <strong>Sam Spade</strong>
        <%= link_to "[Your Account]", "#" %> |
        <%= link_to "[Logout]", "#" %>
      </p>
    </nav>
    <%= link_to(
          image_tag("logo.png",
                    alt: "Artflow",
                    id: "logo"),
          root_url,
          title: "Dashboard") %>
    <%# START_HIGHLIGHT %>
   <%= yield :main_navigation %>
    <%# END_HIGHLIGHT %>
  </header>

app/views/layouts/_header.v1.html.erb
  <header id="page_header">
  </header>

app/views/layouts/_header.v2.html.erb
  <header id="page_header" role="banner">
    <nav id="utility">
      <p>
        You are logged in as <strong>Sam Spade</strong>
        <%= link_to "[Your Account]", "#" %> |
        <%= link_to "[Logout]", "#" %>
      </p>
    </nav>
    <%= link_to(
          image_tag("logo.png",
                    alt: "Artflow",
                    id: "logo"),
          root_url,
          title: "Dashboard") %>
  </header>

app/views/layouts/_header.v3.html.erb
  <header id="page_header" role="banner">
    <nav id="utility">
      <p>
        You are logged in as <strong>Sam Spade</strong>
        <%= link_to "[Your Account]", "#" %> |
        <%= link_to "[Logout]", "#" %>
      </p>
    </nav>
    <%= link_to(
          image_tag("logo.png",
                    alt: "Artflow",
                    id: "logo"),
          root_url,
          title: "Dashboard") %>
    <%# START_HIGHLIGHT %>
    <nav id="main_nav" role="navigation">
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Creations', creations_path %></li>
        <li><%= link_to 'Campaigns', campaigns_path %></li>
        <li><%= link_to 'Projects', projects_path %></li>
        <li><%= link_to 'Designers', designers_path %></li>
      </ul>
    </nav>
    <%# END_HIGHLIGHT %>
  </header>

app/views/layouts/_header.v4.html.erb
  <header id="page_header" role="banner">
    <nav id="utility">
      <p>
        You are logged in as <strong>Sam Spade</strong>
        <%= link_to "[Your Account]", "#" %> |
        <%= link_to "[Logout]", "#" %>
      </p>
    </nav>
    <%= link_to(
          image_tag("logo.png",
                    alt: "Artflow",
                    id: "logo"),
          root_url,
          title: "Dashboard") %>
    <%# START_HIGHLIGHT %>
   <%= yield :main_navigation %>
    <%# END_HIGHLIGHT %>
  </header>

app/views/layouts/_main_nav.html.erb
<% content_for :main_navigation do %>
  <nav id="main_nav" role="navigation">
    <ul>
      <%# START_HIGHLIGHT %>
      <%= nav_tab 'Home',        root_path,        current: current_tab %>
      <%= nav_tab 'Creations',   creations_path,   current: current_tab %>
      <%= nav_tab 'Campaigns',   campaigns_path,   current: current_tab %>
      <%= nav_tab 'Projects',    projects_path,    current: current_tab %>
      <%= nav_tab 'Designers',   designers_path,   current: current_tab %>
      <%# END_HIGHLIGHT %>
    </ul>
  </nav>
<% end %>

app/views/layouts/_main_nav.v1.html.erb
<%# START_HIGHLIGHT %>
<% content_for :main_navigation do %>
<%# END_HIGHLIGHT %>
<nav id="main_nav" role="navigation">
  <ul>
    <li><%= link_to 'Home',      root_path %></li>
    <li><%= link_to 'Creations', creations_path %></li> 
    <li><%= link_to 'Campaigns', campaigns_path %></li>
    <li><%= link_to 'Projects',  projects_path %></li>
    <li><%= link_to 'Designers', designers_path %></li>
  </ul>
</nav>
<%# START_HIGHLIGHT %>
<% end %>
<%# END_HIGHLIGHT %>

app/views/layouts/application.v10.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>
    <% if content_for?(:title) %>
      ArtFlow: <%= yield :title %>
    <% else %>
      Artflow
    <% end %>
  </title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= image_tag("tagline.png",
                alt: "Creative File Management Made Easy",
                id: "tagline") %>
  <div class="container">
    <section id="content">
      <%= yield %>
    </section>
    <section id="sidebar">
      <%= yield :sidebar %>
      <section id="recent_activity">
        <header><h1 class="ir" id="recent">Recent Activity</h1></header>
        <%= render partial: 'activity_items/recent' %>
      </section>
    </section>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/application.v11.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>
    <% if content_for?(:title) %>
      ArtFlow: <%= yield :title %>
    <% else %>
      Artflow
    <% end %>
  </title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= image_tag("tagline.png",
                alt: "Creative File Management Made Easy",
                id: "tagline") %>
  <div class="container">
    <section id="content">
      <%= yield %>
    </section>
    <%# START:sidebar %>
    <section id="sidebar">
      <nav id="functional_nav">
        <ul>
          <% if current_user && current_user.designer? %>
            <li><%= link_to 'Add Creation', new_creation_path %></li>
          <% end %>
          <%= yield :functional_nav %>
        </ul>
      </nav>
      <%= yield :sidebar %>
      <section id="recent_activity">
        <header><h1 class="ir" id="recent">Recent Activity</h1></header>
        <%= render partial: 'activity_items/recent' %>
      </section>
    </section>
    <%# END:sidebar %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/application.v4.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Artflow</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= image_tag("tagline.png",
                alt: "Creative File Management Made Easy",
                id: "tagline") %>
  <div class="container">

    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.v5.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Artflow</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'layouts/header' %>
  <%= image_tag("tagline.png",
                alt: "Creative File Management Made Easy",
                id: "tagline") %>
  <div class="container">

    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/application.v6.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Artflow</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= image_tag("tagline.png",
                alt: "Creative File Management Made Easy",
                id: "tagline") %>
  <div class="container">
    <%# START_HIGHLIGHT %>
    <section id="content">
      <%= yield %>
    </section>
    <section id="sidebar">
    </section>
    <%# END_HIGHLIGHT %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/application.v9.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <%# START:title %>
  <title>
    <% if content_for?(:title) %>
      ArtFlow: <%= yield :title %>
    <% else %>
      Artflow
    <% end %>
  </title>
  <%# END:title %>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= image_tag("tagline.png",
                alt: "Creative File Management Made Easy",
                id: "tagline") %>
  <div class="container">
    <section id="content">
      <%= yield %>
    </section>
    <section id="sidebar">
      <%= yield :sidebar %>
      <section id="recent_activity">
        <header><h1 class="ir" id="recent">Recent Activity</h1></header>
        <%= render partial: 'activity_items/recent' %>
      </section>
    </section>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>